stages:
  - terraform_init_validate
  - terraform_plan
  - infracost
  - terraform_apply

# Définition des jobs pour chaque étape
terraform_init_validate:
  stage: terraform_init_validate
  script:
    - terraform init
    - terraform validate

terraform_plan:
  stage: terraform_plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan

infracost:
  stage: infracost
  script:
    - infracost --tfjson tfplan.json

terraform_apply:
  stage: terraform_apply
  script:
    - |
      if [ "$CI_COMMIT_BRANCH" == "production" ]; then
        terraform apply tfplan
      else
        echo "Manual validation required for applying changes to infrastructure."
      fi
  when: manual
  allow_failure: false
