name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Run InfraCost
        run: |
          # Votre commande pour exécuter InfraCost ici

      - name: Wait for Approval
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          echo "Please approve the Terraform changes in the Pull Request comments."

      - name: Terraform Apply
        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, 'approve') && github.event.issue.pull_request
        run: terraform apply tfplan
        env:
          TF_CLI_ARGS: "-auto-approve"
