name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Run InfraCost
        run: |
          # Votre commande pour exécuter InfraCost ici

      - name: Manual Approval
        if: github.event_name == 'push'
        uses: wei/ci-approval@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Please review and approve the Terraform changes.'

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event_name == 'push' && github.event.action == 'closed'
        run: terraform apply tfplan
        env:
          TF_CLI_ARGS: "-auto-approve"
